<%@ Page Title="" Language="C#" MasterPageFile="~/View/MasterWebApp.Master" AutoEventWireup="true" CodeBehind="IndexStaff.aspx.cs" Inherits="ramenAOL.View.IndexStaff" %>
<asp:Content ID="Content1" ContentPlaceHolderID="contentBody" runat="server">
    <h1>ini untuk staff</h1>
    <div>
        <asp:GridView ID="ramenGV" runat="server" OnRowDeleting="ramenGV_RowDeleting" OnRowUpdating="ramenGV_RowUpdating" OnRowEditing="ramenGV_RowEditing" OnRowCancelingEdit="ramenGV_RowCancelingEdit" OnSelectedIndexChanging="ramenGV_SelectedIndexChanging" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>
    </div>
    <div>
        <br />
        <asp:Label ID="lblStatus" runat="server" Text="[Status]"></asp:Label>
    </div>
</asp:Content>
