<%@ Page Title="" Language="C#" MasterPageFile="~/View/Navbar/StaffNavbar.Master" AutoEventWireup="true" CodeBehind="ManageRamen.aspx.cs" Inherits="ramenAOL.View.Ramen.ManageRamen" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="../css/style.css" rel="stylesheet" />
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="contentBody" runat="server">
<%--    <h1>ini manage ramen page</h1>
    <h2>bisa diakses oleh staff, dan admin</h2>--%>
    <div class="header_top">
        <h1 class="headerNav">Ramen List</h1>
        <div class="btnInsertHeader">
            <asp:Button CssClass="btnInsertRamen" ID="btnInsertRamen" runat="server" Text="Insert Ramen" OnClick="btnInsertRamen_Click" />
        </div>
    </div>

    <div>
        <asp:GridView ID="ramenGV" runat="server" OnRowDeleting="ramenGV_RowDeleting" AutoGenerateDeleteButton="true" OnRowEditing="ramenGV_RowEditing" AutoGenerateEditButton="true"></asp:GridView>
    </div>


</asp:Content>
